server {
    listen 3001; # MUST match your EXPOSE port
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # This is crucial for React Router so refreshing pages doesn't 404
    location / {
        try_files $uri $uri/ /index.html;
    }
}
