apiVersion: v1
kind: Service
metadata:
  name: dogood-web-service
spec:
  type: NodePort
  selector:
    app: dogood-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Matches your VirtualBox Port Forwarding rule
