apiVersion: v1
kind: Service
metadata:
  name: dogood-web-service
spec:
  type: NodePort
  selector:
    app: dogood-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001 # Matches your Dockerfile EXPOSE port
      nodePort: 30080  # MUST be between 30000 and 32767
